name: Checkout
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        uses: actions/checkout@v4.2.2
        with:
          azure-devops-project-url: ${{ }}
          azure-pipeline-name: ''
          azure-devops-token: ${{ }}
        
      
      
